# Generated by Django 3.2 on 2022-06-27 02:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0011_alter_stock_product_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the promotion.', max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(help_text='Slug of the promotion.', max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(help_text='format: required, max_length=700', max_length=700, verbose_name='Promotion description')),
                ('promotion_code', models.CharField(help_text='Promotion code.', max_length=100, unique=True, verbose_name='Promotion code')),
                ('promotion_reduction', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='End date')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time of creation.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of last update.', verbose_name='Updated at')),
                ('products_inventory_in_promotion', models.ManyToManyField(blank=True, related_name='products_promotions', to='inventory.ProductInventory')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-created_at'],
            },
        ),
    ]
