# Generated by Django 3.2 on 2022-06-29 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_stock_product_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.PositiveIntegerField(help_text='Requested quantity.', verbose_name='Requested quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('answer_sent', models.BooleanField(default=False, help_text='Answer send.', verbose_name='Answer send')),
                ('requested_attributes_values', models.ManyToManyField(help_text='Requested attributes values.', to='inventory.ProductAttributeValue', verbose_name='Requested attributes values')),
                ('requested_product', models.ForeignKey(help_text='Requested product.', on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Requested product')),
                ('requested_user', models.ForeignKey(help_text='Requested user.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Requested user')),
            ],
            options={
                'verbose_name': 'Stock email notification',
                'verbose_name_plural': 'Stock email notifications',
            },
        ),
    ]
