# Generated by Django 3.2 on 2022-06-30 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_stock_product_inventory'),
        ('email_notifications', '0003_rename_requested_user_stockemailnotification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockemailnotification',
            name='requested_product',
            field=models.ForeignKey(help_text='Requested product.', on_delete=django.db.models.deletion.CASCADE, related_name='email', to='inventory.product', verbose_name='Requested product'),
        ),
    ]
