# Generated by Django 3.2 on 2022-06-30 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_stock_product_inventory'),
        ('email_notifications', '0004_alter_stockemailnotification_requested_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockemailnotification',
            name='requested_attributes_values',
            field=models.ManyToManyField(help_text='Requested attributes values.', related_name='email_attributes_values', to='inventory.ProductAttributeValue', verbose_name='Requested attributes values'),
        ),
        migrations.AlterField(
            model_name='stockemailnotification',
            name='requested_product',
            field=models.ForeignKey(help_text='Requested product.', on_delete=django.db.models.deletion.CASCADE, related_name='email_product', to='inventory.product', verbose_name='Requested product'),
        ),
    ]
