# Generated by Django 3.2 on 2022-06-08 05:38

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_rename_roles_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='format: required, max_length=50', max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(help_text='format: required, max_length=50', max_length=50, verbose_name='Last name')),
                ('birthday', models.DateField(blank=True, help_text='format: not required', null=True, verbose_name='Birthday')),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar')),
                ('subscription', models.BooleanField(default=False, help_text='format: not required', verbose_name='Subscription')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('role', models.ForeignKey(default=1, help_text='format: not required', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.role', verbose_name='Role')),
                ('user', models.OneToOneField(help_text='format: required, unique=True', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
