# Generated by Django 3.2 on 2022-06-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, help_text='format: not required, max_length=50', max_length=50, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, help_text='format: not required, max_length=50', max_length=50, null=True, verbose_name='Last name'),
        ),
    ]
