# Generated by Django 3.2 on 2022-06-08 06:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220608_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='static/images/default_avatar.svg', max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
