# Generated by Django 3.2 on 2022-06-08 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postal_code',
            new_name='zip_code',
        ),
    ]
