# Generated by Django 3.2 on 2022-06-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_rename_postal_code_address_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(help_text='format: required, max_length=10', max_length=10, verbose_name='Zip code'),
        ),
    ]
