# Generated by Django 3.2 on 2022-06-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20220613_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required, max_length=100', max_length=100, unique=True, verbose_name='Brand name')),
                ('slug', models.SlugField(help_text='format: required, max_length=150', max_length=150, unique=True, verbose_name='Brand Slug')),
                ('description', models.TextField(help_text='format: required, max_length=500', max_length=500, verbose_name='Brand description')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
    ]
