# Generated by Django 3.2 on 2022-06-13 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required, max_length=100', max_length=150, unique=True, verbose_name='Product name')),
                ('slug', models.SlugField(help_text='format: required, max_length=150', max_length=150, unique=True, verbose_name='Product Slug')),
                ('description', models.TextField(help_text='format: required, max_length=500', max_length=500, verbose_name='Product description')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('brand', models.ForeignKey(help_text='format: required, max_length=100', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(help_text='format: required, max_length=100', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category', verbose_name='Category')),
                ('tags', models.ManyToManyField(help_text='format: required, max_length=100', related_name='products', to='inventory.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
