# Generated by Django 3.2 on 2022-06-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='format: required, max_length=100', max_length=100, null=True, unique=True, verbose_name='Product type name')),
                ('slug', models.SlugField(blank=True, help_text='format: required, max_length=150', max_length=150, null=True, unique=True, verbose_name='Product type Slug')),
                ('description', models.TextField(help_text='format: required, max_length=500', max_length=500, verbose_name='Product type description')),
            ],
            options={
                'verbose_name': 'Product type',
                'verbose_name_plural': 'Product types',
                'ordering': ['name'],
            },
        ),
    ]
