# Generated by Django 3.2 on 2022-06-14 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20220613_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinventory',
            options={'ordering': ['sku'], 'verbose_name': 'Product inventory', 'verbose_name_plural': 'Product inventories'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['product_inventory'], 'verbose_name': 'Stock Current'},
        ),
        migrations.AddField(
            model_name='stock',
            name='units_variable',
            field=models.IntegerField(default=0, verbose_name='Units variable'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='inventory.productinventory'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='units',
            field=models.IntegerField(default=0, verbose_name='Units current'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='units_sold',
            field=models.IntegerField(default=0, verbose_name='Units sold'),
        ),
    ]
