# Generated by Django 3.2 on 2022-06-15 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20220614_0754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['product_inventory'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterField(
            model_name='productattributevalues',
            name='attributevalues',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributevalues', to='inventory.productattributevalue'),
        ),
        migrations.AlterField(
            model_name='productattributevalues',
            name='productinventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productattributevalues', to='inventory.productinventory'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='store_price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
