# Generated by Django 3.2 on 2022-06-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20220615_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='default_image',
            field=models.BooleanField(default=False),
        ),
    ]
