# Generated by Django 3.2 on 2022-06-19 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_productimage_default_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product_inventory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock', to='inventory.productinventory'),
        ),
    ]
