# Generated by Django 3.2 on 2022-07-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_key',
            new_name='order_number',
        ),
    ]
